<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Cipher Me!',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
        $items['cipher_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $form['phrase'] = array(
        '#title' => 'Words to cipher',
        '#type' => 'textfield',
        '#description' => t(''),
    );

    $form['shift_value'] = array(
        '#title' => 'How many spots would you like this to be shifted?',
        '#type' => 'textfield',
        '#description' => t(''),
    );

    $form['shift_direction'] = array(
        '#title' => 'Which direction would you like your phrase to be shifted? Left or Right?',
        '#type' => 'textfield',
        '#description' => t(''),
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
}

function element_validate_direction($element) {
    if (!(strtolower($element['#value']) == 'right' || strtolower($element['#value']) == 'left')){
    form_error($element, t('Please choose either left or right.'));
    }
}

// function cipher_form_submit($form, &$form_state) {
//
//     $phrase = $form_state['values']['phrase'];
//     $shift_value = $form_state['values']['shift_value'];
//     $shift_direction = $form_state['values']['shift_direction'];
//
//     $split_input = str_split($phrase);
//
//     $alphabet = 'abcdefghijklmnopqrstuvwxyz';
//
//     $answer = array();
//
//     for ($i=-1; $i < strlen($phrase) ; $i++) {
//         if(in_array($phrase, $alphabet)) {
//             $input_words[$i] = $alphabet[$i+$shift_value];
//             array_push($answer, $alphabet[$i+$shift_value]);
//         } else {
//             array_push($answer, $input_words);
//         }
//     }
//     echo '<pre>';
//     var_dump($answer);
//     echo '</pre>';
//     exit;
// }
